-- Create documents table
-- Migration: 005-create-documents.sql

CREATE TABLE documents (
    -- generated by the application (not gen_random_uuid()) so the same
    -- UUID can be reused as the basis for the storage key
    id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    original_filename VARCHAR(255) NOT NULL,
    storage_key VARCHAR(512) NOT NULL UNIQUE,
    mime_type VARCHAR(100) NOT NULL,
    -- INTEGER (not BIGINT): max value ~2GB comfortably covers MAX_FILE_SIZE_MB,
    -- and avoids pg returning this column as a string (its BIGINT/int8 behavior)
    size_bytes INTEGER NOT NULL,
    page_count INTEGER,
    -- no ON DELETE CASCADE: deleting a user is a soft-delete, documents remain
    user_id UUID NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX documents_user_id_idx ON documents (user_id);
